### ISSUE TITLE
hello,When I install jpmml-xgboost from mvn clean install, everything is fine, but the following error occurs when I install jpmml-catboost. What should I do?

### ISSUE THREAD

**Issue by bambooheng** [jpmml/jpmml-catboost#6] opened 2021-06-27 14:40 UTC
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:exec (default) on project jpmml-catboost: Command execution failed. Cannot run program "D:\apps\jpmml-catboost-master\target\bin\flatc" (in directory "D:\apps\jpmml-catboost-master\src\main\fbs"): CreateProcess error=193, %1 不是有效的 Win32 应用程序。 -> [Help 1]

**Comment by vruusmann** [comment] 2021-06-27 15:37
Exact duplicate of https://github.com/jpmml/jpmml-catboost/issues/5

The resolution is the same.

**Closed as completed by vruusmann** 2021-06-27 15:37 UTC
