### ISSUE TITLE
FlatBuffers compilation is OS/platform-dependent

### ISSUE THREAD

**Issue by bambooheng** [jpmml/jpmml-catboost#5] opened 2021-06-26 06:45 UTC

**Comment by vruusmann** [comment] 2021-06-26 14:32
Closing as duplicate of https://github.com/jpmml/jpmml-catboost/issues/1 and/or https://github.com/jpmml/jpmml-catboost/issues/3

**Closed as completed by vruusmann** 2021-06-26 14:32 UTC

**Comment by BaichaoLIU** [comment] 2022-10-24 00:49
how to solve this question?
